# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The iScientist
email: iscijournal@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 The iScientist is McMaster University's undergraduate interdisciplinary research journal.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
color: "#47c76e"
facebook_username: theiscientist
timezone: America/Toronto
copyright: "The iScientist"
acknowledge-web-author: false
collections:
  volumes:
    output: true
  fields:
    output: true
  events:
    output: true
  eventsUpcoming:
    output: true
  staff:
    output: true
  notices:
    output: false
# For frontpage carousel
carousel:
  - image: Joshi2017MineralOnGypsumPlate-min.jpg
    caption: "Mineral on a Gypsum Plate"
    pc: "Dhvanil Joshi"
    date: 2017
  - image: Joshi2017Mineral-min.jpg
    caption: "Photomicrograph of a Mineral"
    pc: "Dhvanil Joshi"
    date: 2017
  - image: Panuelos2016TurkeyPoint-min.jpg
    caption: "Atop a weather observations tower at Turkey Point, ON"
    pc: "Jonathan Panuelos"
    date: 2016
  - image: Panuelos2016WeatherTower-min.jpg
    caption: "Weather observations tower at Turkey Point, ON"
    pc: "Jonathan Panuelos"
    date: 2016
  - image: Panuelos2013KohlerIllumination-min.jpg
    caption: "Performing Köhler illumination on Nissl-stained mouse brain tissue"
    pc: "Jonathan Panuelos"
    date: 2013
  - image: Panuelos2015CootesPanorama-min.jpg
    caption: "Panorama of Cootes paradise, Hamilton ON"
    pc: "Jonathan Panuelos"
    date: 2015
  - image: Panuelos2018Anatolius-min.jpg
    caption: "Sculpture of Greek mathematician Anatolius residing in Hamilton Hall, McMaster University, Hamilton ON"
    pc: "Jonathan Panuelos"
    date: 2018
    contain: True
  - image: Lai2017WildViolet-min.jpg
    caption: "Wild violet (<i>Viola</i> spp.)"
    pc: "James Lai"
    date: 2017
  - image: Lai2017WhiteTailedDeer-min.jpg
    caption: "White Tailed Deer (<i>Odocoileus virginianus</i>)"
    pc: "James Lai"
    date: 2017
    contain: True
  - image: Lai2017SaskatchewanGlacier-min.jpg
    caption: "Saskatchewan glacier"
    pc: "James Lai"
    date: 2017
  - image: Simon2017Monkey-min.jpg
    caption: "Monkey in Zhangjiajie, Hunan, China"
    pc: "Chris Simon"
    date: 2017
    contain: True
  - image: Simon2017Droplets-min.jpg
    caption: "Intriguing droplets on a leaf in Zhangjiajie, Hunan, China"
    pc: "Chris Simon"
    date: 2017
  - image: Simon2017River-min.jpg
    caption: "Flowing river in Zhangjiajie, Hunan, China"
    pc: "Chris Simon"
    date: 2017
  - image: Chong2017DundasPeak-min.jpg
    caption: "Dundas peak, Hamilton, ON"
    pc: "Michael Chong"
    date: 2017
  - image: Edwards2017Elephant-min.jpg
    caption: "African Bush Elephant (<i>Loxodonta africana</i>) in Tsavo, Kenya"
    pc: "Ross Edwards"
    date: 2017
  - image: Edwards2017GiantGroundsel-min.jpg
    caption: "Giant Groundsel (<i>Dendrosenecio keniodendron</i>) on Mount Kenya"
    pc: "Ross Edwards"
    date: 2017
  - image: Edwards2017WindEnergy-min.jpg
    caption: "Wind Energy on Ngong Hills, Kenya"
    pc: "Ross Edwards"
    date: 2017



# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
